# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab_08_design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 900))
        MainWindow.setStyleSheet("background-color: rgb(222, 255, 215);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(11, 11, 1573, 882))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(7, 7, 10, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.scene = QtWidgets.QGraphicsScene()
        self.scene.setSceneRect(0, 0, 1190, 870)
        self.canvas = QtWidgets.QGraphicsView(self.scene, self.widget)
        self.canvas.setMinimumSize(QtCore.QSize(1200, 880))
        self.canvas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.canvas.setObjectName("canvas")
        self.gridLayout.addWidget(self.canvas, 0, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.widget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setHandleWidth(15)
        self.splitter_3.setObjectName("splitter_3")
        self.radio_cutter = QtWidgets.QRadioButton(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.radio_cutter.setFont(font)
        self.radio_cutter.setChecked(True)
        self.radio_cutter.setObjectName("radio_cutter")
        self.radio_line = QtWidgets.QRadioButton(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.radio_line.setFont(font)
        self.radio_line.setObjectName("radio_line")
        self.label = QtWidgets.QLabel(self.splitter_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.cutter_box = QtWidgets.QComboBox(self.splitter_3)
        self.cutter_box.setMaximumSize(QtCore.QSize(361, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cutter_box.setFont(font)
        self.cutter_box.setStyleSheet("selection-color: rgb(0, 0, 0);")
        self.cutter_box.setObjectName("cutter_box")
        self.cutter_box.addItem("")
        self.cutter_box.addItem("")
        self.cutter_box.addItem("")
        self.cutter_box.addItem("")
        self.cutter_box.addItem("")
        self.cutter_box.addItem("")
        self.cutter_box.addItem("")
        self.cutter_box.addItem("")
        self.vertex_label = QtWidgets.QLabel(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertex_label.sizePolicy().hasHeightForWidth())
        self.vertex_label.setSizePolicy(sizePolicy)
        self.vertex_label.setMinimumSize(QtCore.QSize(171, 0))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.vertex_label.setFont(font)
        self.vertex_label.setAlignment(QtCore.Qt.AlignCenter)
        self.vertex_label.setObjectName("vertex_label")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(29)
        self.splitter.setObjectName("splitter")
        self.vertex_x_label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertex_x_label.sizePolicy().hasHeightForWidth())
        self.vertex_x_label.setSizePolicy(sizePolicy)
        self.vertex_x_label.setMinimumSize(QtCore.QSize(166, 0))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.vertex_x_label.setFont(font)
        self.vertex_x_label.setAlignment(QtCore.Qt.AlignCenter)
        self.vertex_x_label.setObjectName("vertex_x_label")
        self.vertex_y_label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertex_y_label.sizePolicy().hasHeightForWidth())
        self.vertex_y_label.setSizePolicy(sizePolicy)
        self.vertex_y_label.setMinimumSize(QtCore.QSize(166, 0))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.vertex_y_label.setFont(font)
        self.vertex_y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.vertex_y_label.setObjectName("vertex_y_label")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(29)
        self.splitter_2.setObjectName("splitter_2")
        self.ver_x_entry = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ver_x_entry.setFont(font)
        self.ver_x_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ver_x_entry.setObjectName("ver_x_entry")
        self.ver_y_entry = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ver_y_entry.setFont(font)
        self.ver_y_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ver_y_entry.setObjectName("ver_y_entry")
        self.vertex_btn = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertex_btn.sizePolicy().hasHeightForWidth())
        self.vertex_btn.setSizePolicy(sizePolicy)
        self.vertex_btn.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.vertex_btn.setFont(font)
        self.vertex_btn.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.vertex_btn.setObjectName("vertex_btn")
        self.close_btn = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.close_btn.setObjectName("close_btn")
        self.label_2 = QtWidgets.QLabel(self.splitter_3)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.line_box = QtWidgets.QComboBox(self.splitter_3)
        self.line_box.setMaximumSize(QtCore.QSize(361, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.line_box.setFont(font)
        self.line_box.setStyleSheet("selection-color: rgb(0, 0, 0);")
        self.line_box.setObjectName("line_box")
        self.line_box.addItem("")
        self.line_box.addItem("")
        self.line_box.addItem("")
        self.line_box.addItem("")
        self.line_box.addItem("")
        self.line_box.addItem("")
        self.line_box.addItem("")
        self.line_box.addItem("")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setHandleWidth(29)
        self.splitter_5.setObjectName("splitter_5")
        self.x_label = QtWidgets.QLabel(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_label.sizePolicy().hasHeightForWidth())
        self.x_label.setSizePolicy(sizePolicy)
        self.x_label.setMinimumSize(QtCore.QSize(166, 0))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.x_label.setFont(font)
        self.x_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_label.setObjectName("x_label")
        self.y_label = QtWidgets.QLabel(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_label.sizePolicy().hasHeightForWidth())
        self.y_label.setSizePolicy(sizePolicy)
        self.y_label.setMinimumSize(QtCore.QSize(166, 0))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.y_label.setFont(font)
        self.y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_label.setObjectName("y_label")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setHandleWidth(29)
        self.splitter_6.setObjectName("splitter_6")
        self.x_entry = QtWidgets.QLineEdit(self.splitter_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x_entry.setFont(font)
        self.x_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x_entry.setObjectName("x_entry")
        self.y_entry = QtWidgets.QLineEdit(self.splitter_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.y_entry.setFont(font)
        self.y_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.y_entry.setObjectName("y_entry")
        self.add_btn = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_btn.sizePolicy().hasHeightForWidth())
        self.add_btn.setSizePolicy(sizePolicy)
        self.add_btn.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.add_btn.setObjectName("add_btn")
        self.label_3 = QtWidgets.QLabel(self.splitter_3)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.result_box = QtWidgets.QComboBox(self.splitter_3)
        self.result_box.setMaximumSize(QtCore.QSize(361, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.result_box.setFont(font)
        self.result_box.setStyleSheet("selection-color: rgb(0, 0, 0);")
        self.result_box.setObjectName("result_box")
        self.result_box.addItem("")
        self.result_box.addItem("")
        self.result_box.addItem("")
        self.result_box.addItem("")
        self.result_box.addItem("")
        self.result_box.addItem("")
        self.result_box.addItem("")
        self.result_box.addItem("")
        self.cut_btn = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cut_btn.sizePolicy().hasHeightForWidth())
        self.cut_btn.setSizePolicy(sizePolicy)
        self.cut_btn.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cut_btn.setFont(font)
        self.cut_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.cut_btn.setObjectName("cut_btn")
        self.label_4 = QtWidgets.QLabel(self.splitter_3)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setHandleWidth(29)
        self.splitter_7.setObjectName("splitter_7")
        self.clear_btn = QtWidgets.QPushButton(self.splitter_7)
        self.clear_btn.setMinimumSize(QtCore.QSize(161, 0))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(78, 154, 6);")
        self.clear_btn.setObjectName("clear_btn")
        self.exit_btn = QtWidgets.QPushButton(self.splitter_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setMinimumSize(QtCore.QSize(161, 0))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(164, 0, 0);")
        self.exit_btn.setObjectName("exit_btn")
        self.gridLayout.addWidget(self.splitter_3, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Алгоритм отсечения Кириуса-Бека"))
        self.radio_cutter.setText(_translate("MainWindow", "Ввод отсекателя"))
        self.radio_line.setText(_translate("MainWindow", "Ввод отрезков"))
        self.cutter_box.setItemText(0, _translate("MainWindow", "Цвет отсекателя..."))
        self.cutter_box.setItemText(1, _translate("MainWindow", "Красный"))
        self.cutter_box.setItemText(2, _translate("MainWindow", "Синий"))
        self.cutter_box.setItemText(3, _translate("MainWindow", "Черный"))
        self.cutter_box.setItemText(4, _translate("MainWindow", "Зеленый"))
        self.cutter_box.setItemText(5, _translate("MainWindow", "Оранжевый"))
        self.cutter_box.setItemText(6, _translate("MainWindow", "Фиолетовый"))
        self.cutter_box.setItemText(7, _translate("MainWindow", "Белый"))
        self.vertex_label.setText(_translate("MainWindow", "Ввод вершины отсекателя"))
        self.vertex_x_label.setText(_translate("MainWindow", "X:"))
        self.vertex_y_label.setText(_translate("MainWindow", "Y:"))
        self.vertex_btn.setText(_translate("MainWindow", "Добавить вершину"))
        self.close_btn.setText(_translate("MainWindow", "Замкнуть отсекатель"))
        self.line_box.setItemText(0, _translate("MainWindow", "Цвет отрезков..."))
        self.line_box.setItemText(1, _translate("MainWindow", "Красный"))
        self.line_box.setItemText(2, _translate("MainWindow", "Синий"))
        self.line_box.setItemText(3, _translate("MainWindow", "Черный"))
        self.line_box.setItemText(4, _translate("MainWindow", "Зеленый"))
        self.line_box.setItemText(5, _translate("MainWindow", "Оранжевый"))
        self.line_box.setItemText(6, _translate("MainWindow", "Фиолетовый"))
        self.line_box.setItemText(7, _translate("MainWindow", "Белый"))
        self.x_label.setText(_translate("MainWindow", "X:"))
        self.y_label.setText(_translate("MainWindow", "Y:"))
        self.add_btn.setText(_translate("MainWindow", "Добавить точку"))
        self.result_box.setItemText(0, _translate("MainWindow", "Цвет результата..."))
        self.result_box.setItemText(1, _translate("MainWindow", "Красный"))
        self.result_box.setItemText(2, _translate("MainWindow", "Синий"))
        self.result_box.setItemText(3, _translate("MainWindow", "Черный"))
        self.result_box.setItemText(4, _translate("MainWindow", "Зеленый"))
        self.result_box.setItemText(5, _translate("MainWindow", "Оранжевый"))
        self.result_box.setItemText(6, _translate("MainWindow", "Фиолетовый"))
        self.result_box.setItemText(7, _translate("MainWindow", "Белый"))
        self.cut_btn.setText(_translate("MainWindow", "Применить отсечение"))
        self.clear_btn.setText(_translate("MainWindow", "Очистить"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))
