# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setStyleSheet("background-color: rgb(223, 177, 217);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1600, 900))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.scene = QtWidgets.QGraphicsScene()
        self.scene.setSceneRect(0, 0, 1195, 869)
        self.canvas = QtWidgets.QGraphicsView(self.scene, self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(5, 11, 1200, 880))
        self.canvas.setStyleSheet("background-color: rgb(235, 237, 255);")
        self.canvas.setMidLineWidth(4)
        self.canvas.setObjectName("canvas")
        self.info_btn = QtWidgets.QPushButton(self.centralwidget)
        self.info_btn.setGeometry(QtCore.QRect(1240, 830, 151, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.info_btn.setFont(font)
        self.info_btn.setStyleSheet("background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);")
        self.info_btn.setObjectName("info_btn")
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(1410, 830, 151, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("background-color: rgb(205, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.exit_btn.setObjectName("exit_btn")
        self.entry_dx = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_dx.setGeometry(QtCore.QRect(1240, 120, 151, 41))
        self.entry_dx.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_dx.setObjectName("entry_dx")
        self.entry_dy = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_dy.setGeometry(QtCore.QRect(1410, 120, 151, 41))
        self.entry_dy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_dy.setObjectName("entry_dy")
        self.entry_cx = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_cx.setGeometry(QtCore.QRect(1240, 320, 151, 41))
        self.entry_cx.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_cx.setObjectName("entry_cx")
        self.entry_cy = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_cy.setGeometry(QtCore.QRect(1410, 320, 151, 41))
        self.entry_cy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_cy.setObjectName("entry_cy")
        self.entry_kx = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_kx.setGeometry(QtCore.QRect(1240, 430, 151, 41))
        self.entry_kx.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_kx.setObjectName("entry_kx")
        self.entry_ky = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_ky.setGeometry(QtCore.QRect(1410, 430, 151, 41))
        self.entry_ky.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_ky.setObjectName("entry_ky")
        self.entry_angle = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_angle.setGeometry(QtCore.QRect(1240, 610, 321, 41))
        self.entry_angle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_angle.setObjectName("entry_angle")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(1410, 750, 151, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);")
        self.back_btn.setObjectName("back_btn")
        self.origin_btn = QtWidgets.QPushButton(self.centralwidget)
        self.origin_btn.setGeometry(QtCore.QRect(1240, 750, 151, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.origin_btn.setFont(font)
        self.origin_btn.setStyleSheet("background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);")
        self.origin_btn.setObjectName("origin_btn")
        self.scale_btn = QtWidgets.QPushButton(self.centralwidget)
        self.scale_btn.setGeometry(QtCore.QRect(1240, 480, 321, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.scale_btn.setFont(font)
        self.scale_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 95, 180);")
        self.scale_btn.setObjectName("scale_btn")
        self.move_btn = QtWidgets.QPushButton(self.centralwidget)
        self.move_btn.setGeometry(QtCore.QRect(1240, 170, 321, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.move_btn.setFont(font)
        self.move_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 95, 180);")
        self.move_btn.setObjectName("move_btn")
        self.rotate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.rotate_btn.setGeometry(QtCore.QRect(1240, 660, 321, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.rotate_btn.setFont(font)
        self.rotate_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 95, 180);")
        self.rotate_btn.setObjectName("rotate_btn")
        self.label_dx = QtWidgets.QLabel(self.centralwidget)
        self.label_dx.setGeometry(QtCore.QRect(1243, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_dx.setFont(font)
        self.label_dx.setObjectName("label_dx")
        self.label_dy = QtWidgets.QLabel(self.centralwidget)
        self.label_dy.setGeometry(QtCore.QRect(1413, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_dy.setFont(font)
        self.label_dy.setObjectName("label_dy")
        self.label_scale = QtWidgets.QLabel(self.centralwidget)
        self.label_scale.setGeometry(QtCore.QRect(1220, 250, 361, 41))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_scale.setFont(font)
        self.label_scale.setAlignment(QtCore.Qt.AlignCenter)
        self.label_scale.setObjectName("label_scale")
        self.label_cx = QtWidgets.QLabel(self.centralwidget)
        self.label_cx.setGeometry(QtCore.QRect(1233, 290, 161, 31))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_cx.setFont(font)
        self.label_cx.setObjectName("label_cx")
        self.label_kx = QtWidgets.QLabel(self.centralwidget)
        self.label_kx.setGeometry(QtCore.QRect(1237, 400, 161, 31))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_kx.setFont(font)
        self.label_kx.setObjectName("label_kx")
        self.label_ky = QtWidgets.QLabel(self.centralwidget)
        self.label_ky.setGeometry(QtCore.QRect(1409, 400, 161, 31))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ky.setFont(font)
        self.label_ky.setObjectName("label_ky")
        self.label_angle = QtWidgets.QLabel(self.centralwidget)
        self.label_angle.setGeometry(QtCore.QRect(1243, 580, 321, 21))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_angle.setFont(font)
        self.label_angle.setObjectName("label_angle")
        self.label_center = QtWidgets.QLabel(self.centralwidget)
        self.label_center.setGeometry(QtCore.QRect(1220, 20, 371, 41))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_center.setFont(font)
        self.label_center.setAlignment(QtCore.Qt.AlignCenter)
        self.label_center.setObjectName("label_center")
        self.label_cy = QtWidgets.QLabel(self.centralwidget)
        self.label_cy.setGeometry(QtCore.QRect(1407, 290, 161, 31))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_cy.setFont(font)
        self.label_cy.setObjectName("label_cy")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Преобразования фигуры"))
        self.info_btn.setText(_translate("MainWindow", "Справка"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))
        self.back_btn.setText(_translate("MainWindow", "Назад"))
        self.origin_btn.setText(_translate("MainWindow", "К исходной"))
        self.scale_btn.setText(_translate("MainWindow", "Масштабировать"))
        self.move_btn.setText(_translate("MainWindow", "Перенести фигуру"))
        self.rotate_btn.setText(_translate("MainWindow", "Повернуть"))
        self.label_dx.setText(_translate("MainWindow", "Смещение Х"))
        self.label_dy.setText(_translate("MainWindow", "Смещение Y"))
        self.label_scale.setText(_translate("MainWindow", "Центр масштабирования/поворота"))
        self.label_cx.setText(_translate("MainWindow", "Координата Х"))
        self.label_kx.setText(_translate("MainWindow", "Коэффициент kx"))
        self.label_ky.setText(_translate("MainWindow", "Коэффициент ky"))
        self.label_angle.setText(_translate("MainWindow", "Угол поворота (в градусах)"))
        self.label_center.setText(_translate("MainWindow", "Центр фигуры C(x, y)"))
        self.label_cy.setText(_translate("MainWindow", "Координата Y"))
