# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setStyleSheet("background-color: rgb(223, 177, 217);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1600, 900))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(5, 11, 1581, 881))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(7, 7, 10, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.scene = QtWidgets.QGraphicsScene()
        self.scene.setSceneRect(0, 0, 1180, 870)
        self.canvas = QtWidgets.QGraphicsView(self.scene, self.widget)
        self.canvas.setStyleSheet("background-color: rgb(235, 237, 255);")
        self.canvas.setMidLineWidth(4)
        self.canvas.setObjectName("canvas")
        self.gridLayout.addWidget(self.canvas, 0, 0, 1, 1)
        self.splitter_9 = QtWidgets.QSplitter(self.widget)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setHandleWidth(6)
        self.splitter_9.setObjectName("splitter_9")
        self.label_center = QtWidgets.QLabel(self.splitter_9)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_center.setFont(font)
        self.label_center.setAlignment(QtCore.Qt.AlignCenter)
        self.label_center.setObjectName("label_center")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setHandleWidth(11)
        self.splitter_6.setObjectName("splitter_6")
        self.label_dx = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_dx.setFont(font)
        self.label_dx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dx.setObjectName("label_dx")
        self.label_dy = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_dy.setFont(font)
        self.label_dy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dy.setObjectName("label_dy")
        self.splitter = QtWidgets.QSplitter(self.splitter_9)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(19)
        self.splitter.setObjectName("splitter")
        self.entry_dx = QtWidgets.QLineEdit(self.splitter)
        self.entry_dx.setMinimumSize(QtCore.QSize(0, 46))
        self.entry_dx.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.entry_dx.setFont(font)
        self.entry_dx.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_dx.setObjectName("entry_dx")
        self.entry_dy = QtWidgets.QLineEdit(self.splitter)
        self.entry_dy.setMinimumSize(QtCore.QSize(0, 46))
        self.entry_dy.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.entry_dy.setFont(font)
        self.entry_dy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_dy.setObjectName("entry_dy")
        self.move_btn = QtWidgets.QPushButton(self.splitter_9)
        self.move_btn.setMinimumSize(QtCore.QSize(0, 51))
        self.move_btn.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.move_btn.setFont(font)
        self.move_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 95, 180);")
        self.move_btn.setObjectName("move_btn")
        self.label_scale = QtWidgets.QLabel(self.splitter_9)
        self.label_scale.setMinimumSize(QtCore.QSize(0, 63))
        self.label_scale.setMaximumSize(QtCore.QSize(16777215, 63))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_scale.setFont(font)
        self.label_scale.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_scale.setObjectName("label_scale")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.label_cx = QtWidgets.QLabel(self.splitter_7)
        self.label_cx.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_cx.setFont(font)
        self.label_cx.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_cx.setObjectName("label_cx")
        self.label_cy = QtWidgets.QLabel(self.splitter_7)
        self.label_cy.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_cy.setFont(font)
        self.label_cy.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_cy.setObjectName("label_cy")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(19)
        self.splitter_2.setObjectName("splitter_2")
        self.entry_cx = QtWidgets.QLineEdit(self.splitter_2)
        self.entry_cx.setMinimumSize(QtCore.QSize(0, 46))
        self.entry_cx.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.entry_cx.setFont(font)
        self.entry_cx.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_cx.setObjectName("entry_cx")
        self.entry_cy = QtWidgets.QLineEdit(self.splitter_2)
        self.entry_cy.setMinimumSize(QtCore.QSize(0, 46))
        self.entry_cy.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.entry_cy.setFont(font)
        self.entry_cy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_cy.setObjectName("entry_cy")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.label_kx = QtWidgets.QLabel(self.splitter_8)
        self.label_kx.setMinimumSize(QtCore.QSize(0, 46))
        self.label_kx.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_kx.setFont(font)
        self.label_kx.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_kx.setObjectName("label_kx")
        self.label_ky = QtWidgets.QLabel(self.splitter_8)
        self.label_ky.setMinimumSize(QtCore.QSize(0, 46))
        self.label_ky.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ky.setFont(font)
        self.label_ky.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_ky.setObjectName("label_ky")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setHandleWidth(19)
        self.splitter_3.setObjectName("splitter_3")
        self.entry_kx = QtWidgets.QLineEdit(self.splitter_3)
        self.entry_kx.setMinimumSize(QtCore.QSize(0, 46))
        self.entry_kx.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.entry_kx.setFont(font)
        self.entry_kx.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_kx.setObjectName("entry_kx")
        self.entry_ky = QtWidgets.QLineEdit(self.splitter_3)
        self.entry_ky.setMinimumSize(QtCore.QSize(0, 46))
        self.entry_ky.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.entry_ky.setFont(font)
        self.entry_ky.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_ky.setObjectName("entry_ky")
        self.scale_btn = QtWidgets.QPushButton(self.splitter_9)
        self.scale_btn.setMinimumSize(QtCore.QSize(0, 51))
        self.scale_btn.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.scale_btn.setFont(font)
        self.scale_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 95, 180);")
        self.scale_btn.setObjectName("scale_btn")
        self.label_2 = QtWidgets.QLabel(self.splitter_9)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_angle = QtWidgets.QLabel(self.splitter_9)
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_angle.setFont(font)
        self.label_angle.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_angle.setObjectName("label_angle")
        self.entry_angle = QtWidgets.QLineEdit(self.splitter_9)
        self.entry_angle.setMinimumSize(QtCore.QSize(0, 46))
        self.entry_angle.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.entry_angle.setFont(font)
        self.entry_angle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entry_angle.setObjectName("entry_angle")
        self.rotate_btn = QtWidgets.QPushButton(self.splitter_9)
        self.rotate_btn.setMinimumSize(QtCore.QSize(0, 51))
        self.rotate_btn.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.rotate_btn.setFont(font)
        self.rotate_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 95, 180);")
        self.rotate_btn.setObjectName("rotate_btn")
        self.label = QtWidgets.QLabel(self.splitter_9)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setText("")
        self.label.setObjectName("label")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setHandleWidth(19)
        self.splitter_4.setObjectName("splitter_4")
        self.origin_btn = QtWidgets.QPushButton(self.splitter_4)
        self.origin_btn.setMinimumSize(QtCore.QSize(0, 51))
        self.origin_btn.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.origin_btn.setFont(font)
        self.origin_btn.setStyleSheet("background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);")
        self.origin_btn.setObjectName("origin_btn")
        self.back_btn = QtWidgets.QPushButton(self.splitter_4)
        self.back_btn.setMinimumSize(QtCore.QSize(0, 51))
        self.back_btn.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);")
        self.back_btn.setObjectName("back_btn")
        self.label_3 = QtWidgets.QLabel(self.splitter_9)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setHandleWidth(19)
        self.splitter_5.setObjectName("splitter_5")
        self.info_btn = QtWidgets.QPushButton(self.splitter_5)
        self.info_btn.setMinimumSize(QtCore.QSize(0, 51))
        self.info_btn.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.info_btn.setFont(font)
        self.info_btn.setStyleSheet("background-color: rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);")
        self.info_btn.setObjectName("info_btn")
        self.exit_btn = QtWidgets.QPushButton(self.splitter_5)
        self.exit_btn.setMinimumSize(QtCore.QSize(0, 51))
        self.exit_btn.setMaximumSize(QtCore.QSize(171, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("background-color: rgb(205, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.exit_btn.setObjectName("exit_btn")
        self.gridLayout.addWidget(self.splitter_9, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Преобразования фигуры"))
        self.label_center.setText(_translate("MainWindow", "Центр фигуры C(x, y)"))
        self.label_dx.setText(_translate("MainWindow", "Смещение Х"))
        self.label_dy.setText(_translate("MainWindow", "Смещение Y"))
        self.move_btn.setText(_translate("MainWindow", "Перенести фигуру"))
        self.label_scale.setText(_translate("MainWindow", "Центр масштабирования/поворота"))
        self.label_cx.setText(_translate("MainWindow", "Координата Х"))
        self.label_cy.setText(_translate("MainWindow", "Координата Y"))
        self.label_kx.setText(_translate("MainWindow", "Коэффициент kx"))
        self.label_ky.setText(_translate("MainWindow", "Коэффициент ky"))
        self.scale_btn.setText(_translate("MainWindow", "Масштабировать"))
        self.label_angle.setText(_translate("MainWindow", "Угол поворота (в градусах)"))
        self.rotate_btn.setText(_translate("MainWindow", "Повернуть"))
        self.origin_btn.setText(_translate("MainWindow", "К исходной"))
        self.back_btn.setText(_translate("MainWindow", "Назад"))
        self.info_btn.setText(_translate("MainWindow", "Справка"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))
