# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab_05_design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setStyleSheet("background-color: rgb(229, 253, 246);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(11, 11, 1581, 882))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(7, 7, 10, 10)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.scene = QtWidgets.QGraphicsScene()
        self.scene.setSceneRect(5, 11, 1195, 869)
        self.canvas = QtWidgets.QGraphicsView(self.scene, self.widget)
        self.canvas.setMinimumSize(QtCore.QSize(1200, 880))
        self.canvas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.canvas.setObjectName("canvas")
        self.gridLayout.addWidget(self.canvas, 0, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setHandleWidth(19)
        self.splitter_3.setObjectName("splitter_3")
        self.label = QtWidgets.QLabel(self.splitter_3)
        self.label.setMinimumSize(QtCore.QSize(0, 120))
        self.label.setText("")
        self.label.setObjectName("label")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(29)
        self.splitter.setObjectName("splitter")
        self.x_label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_label.sizePolicy().hasHeightForWidth())
        self.x_label.setSizePolicy(sizePolicy)
        self.x_label.setMinimumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.x_label.setFont(font)
        self.x_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_label.setObjectName("x_label")
        self.y_label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_label.sizePolicy().hasHeightForWidth())
        self.y_label.setSizePolicy(sizePolicy)
        self.y_label.setMinimumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.y_label.setFont(font)
        self.y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_label.setObjectName("y_label")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(29)
        self.splitter_2.setObjectName("splitter_2")
        self.x_entry = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x_entry.setFont(font)
        self.x_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.x_entry.setObjectName("x_entry")
        self.x_entry.setMinimumSize(QtCore.QSize(161, 41))
        self.y_entry = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.y_entry.setFont(font)
        self.y_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.y_entry.setObjectName("y_entry")
        self.y_entry.setMinimumSize(QtCore.QSize(161, 41))
        self.add_btn = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_btn.sizePolicy().hasHeightForWidth())
        self.add_btn.setSizePolicy(sizePolicy)
        self.add_btn.setMinimumSize(QtCore.QSize(0, 51))
        self.add_btn.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.add_btn.setFont(font)
        self.add_btn.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.add_btn.setObjectName("add_btn")
        self.label_2 = QtWidgets.QLabel(self.splitter_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 61))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.close_fig_btn = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_fig_btn.sizePolicy().hasHeightForWidth())
        self.close_fig_btn.setSizePolicy(sizePolicy)
        self.close_fig_btn.setMinimumSize(QtCore.QSize(0, 51))
        self.close_fig_btn.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.close_fig_btn.setFont(font)
        self.close_fig_btn.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.close_fig_btn.setObjectName("close_fig_btn")
        self.label_3 = QtWidgets.QLabel(self.splitter_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 61))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.delay_check = QtWidgets.QCheckBox(self.splitter_3)
        self.delay_check.setMinimumSize(QtCore.QSize(0, 51))
        self.delay_check.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.delay_check.setFont(font)
        
        self.delay_check.setObjectName("delay_check")
        self.color_box = QtWidgets.QComboBox(self.splitter_3)
        self.color_box.setMinimumSize(QtCore.QSize(351, 51))
        self.color_box.setMaximumSize(QtCore.QSize(351, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.color_box.setFont(font)
        self.color_box.setStyleSheet("selection-color: rgb(0, 0, 0);\n")
        self.color_box.setObjectName("color_box")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.color_box.addItem("")
        self.fill_btn = QtWidgets.QPushButton(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fill_btn.sizePolicy().hasHeightForWidth())
        self.fill_btn.setSizePolicy(sizePolicy)
        self.fill_btn.setMinimumSize(QtCore.QSize(0, 51))
        self.fill_btn.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.fill_btn.setFont(font)
        self.fill_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.fill_btn.setObjectName("fill_btn")
        self.label_5 = QtWidgets.QLabel(self.splitter_3)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 61))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setHandleWidth(29)
        self.splitter_4.setObjectName("splitter_4")
        self.clear_btn = QtWidgets.QPushButton(self.splitter_4)

        self.clear_btn.setMinimumSize(QtCore.QSize(161, 51))
        self.clear_btn.setMaximumSize(QtCore.QSize(161, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(78, 154, 6);")
        self.clear_btn.setObjectName("clear_btn")
        self.exit_btn = QtWidgets.QPushButton(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setMinimumSize(QtCore.QSize(161, 51))
        self.exit_btn.setMaximumSize(QtCore.QSize(161, 51))
        font = QtGui.QFont()
        font.setFamily("KacstTitle")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(164, 0, 0);")
        self.exit_btn.setObjectName("exit_btn")
        self.label_4 = QtWidgets.QLabel(self.splitter_3)
        self.label_4.setMinimumSize(QtCore.QSize(0, 120))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.splitter_3, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Заполнение многоугольника"))
        self.x_label.setText(_translate("MainWindow", "X:"))
        self.y_label.setText(_translate("MainWindow", "Y:"))
        self.add_btn.setText(_translate("MainWindow", "Добавить точку"))
        self.close_fig_btn.setText(_translate("MainWindow", "Замкнуть многоугольник"))
        self.delay_check.setText(_translate("MainWindow", "Задержка"))
        self.color_box.setItemText(0, _translate("MainWindow", "Цвет заливки..."))
        self.color_box.setItemText(1, _translate("MainWindow", "Красный"))
        self.color_box.setItemText(2, _translate("MainWindow", "Синий"))
        self.color_box.setItemText(3, _translate("MainWindow", "Черный"))
        self.color_box.setItemText(4, _translate("MainWindow", "Белый"))
        self.fill_btn.setText(_translate("MainWindow", "Заполнить"))
        self.clear_btn.setText(_translate("MainWindow", "Очистить"))
        self.exit_btn.setText(_translate("MainWindow", "Выход"))
